import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Provider from "@/modules/chakraProvider/components/Provider";
import BudgetProvider from "@/context/BudgetContext";
import { Container, Flex } from "@chakra-ui/react";
import Navbar from "@/modules/layout/components/Navbar";
import GlobalSelectors from "@/globalSelectors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <BudgetProvider>
            <Flex height='100vh'>
              <Navbar />
              <Container className={GlobalSelectors.MAIN_CONTAINER}>{children}</Container>
            </Flex>
          </BudgetProvider>
        </Provider>
      </body>
    </html>
  );
}
